"""Shared constants for wire-level decorations transform implementation."""

from __future__ import annotations

DEG_HALF_TURN = 180.0
DEG_FULL_TURN = 360.0

EPS_TINY = 1e-12
EPS_EULER_CX = 1e-8

WIRE_TYPE_VARINT = 0
WIRE_TYPE_LENGTH_DELIMITED = 2
WIRE_TYPE_FIXED32 = 5

VECTOR3_FIELD_X = 1
VECTOR3_FIELD_Y = 2
VECTOR3_FIELD_Z = 3
VECTOR3_FIXED32_BYTES = 4

TRANSFORM_FIELD_POS = 1
TRANSFORM_FIELD_ROT_DEG = 2
TRANSFORM_FIELD_SCALE = 3

ROOT_FIELD_PARENTS = 1
ROOT_FIELD_ACCESSORIES = 2
ROOT_FIELD_FILE_PATH = 3

GRAPH_UNIT_FIELD_ID = 1
GRAPH_UNIT_FIELD_RELATED_IDS = 2
GRAPH_UNIT_FIELD_NAME = 3
GRAPH_UNIT_FIELD_COMPONENT_TREE = 12

GRAPH_UNIT_ID_FIELD_UNIT_ID_INT = 4

COMPONENT_TREE_FIELD_ROOT = 1
COMPONENT_TREE_FIELD_ENTRIES = 6
COMPONENT_ENTRY_FIELD_KEY = 1
COMPONENT_ENTRY_KEY_TRANSFORM = 1
COMPONENT_ENTRY_FIELD_TRANSFORM = 11

RELATED_ID_FIELD_UNIT_ID_INT = 4

ACCESSORY_PAYLOAD_FIELD_PARENT_BIND_MAP = 4
ACCESSORY_PARENT_BIND_ENTRY_FIELD_KEY = 1
ACCESSORY_PAYLOAD_PARENT_BIND_KEY = 40
ACCESSORY_PAYLOAD_PARENT_BIND_FIELD_NESTED = 50
ACCESSORY_PARENT_BIND_FIELD_PARENT_UNIT_ID_INT = 502

ACCESSORY_PAYLOAD_FIELD_TRANSFORM_ENTRIES = 5
ACCESSORY_ENTRY_FIELD_TRANSFORM = 11

ACCESSORY_WRAPPER_FIELD_PAYLOAD = 1

PARENT_GRAPH_ENTRY_KEY_FIELD = 1
PARENT_GRAPH_ENTRY_KEY_ACCESSORY_BIND = 40
PARENT_GRAPH_ENTRY_FIELD_BYTES_OR_MESSAGE = 50
PARENT_GRAPH_PACKED_IDS_FIELD_BYTES = 501

PROBE_MAX_DEPTH = 3
PROBE_BYTES_PREVIEW_LENGTH = 32
PROBE_MAX_LENGTH_DELIMITED_STRING_BYTES = 128
PROBE_MAX_PACKED_ITEMS = 256
PROBE_MAX_MESSAGE_BYTES_FOR_PROBE = 4096

