from __future__ import annotations

from typing import Any, Dict

STRUCT_ID = 'struct_all_supported_types_example'
STRUCT_TYPE = 'basic'

STRUCT_PAYLOAD: Dict[str, Any] = {'type': 'Struct',
 'struct_ype': 'basic',
 'name': 'struct_all_supported_types_example',
 'value': [{'key': '实体字段', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}},
           {'key': 'GUID字段', 'param_type': 'Guid', 'value': {'param_type': 'Guid', 'value': '00000000'}},
           {'key': '整数字段', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}},
           {'key': '布尔值字段', 'param_type': 'Bool', 'value': {'param_type': 'Bool', 'value': 'False'}},
           {'key': '浮点数字段', 'param_type': 'Float', 'value': {'param_type': 'Float', 'value': '0.0'}},
           {'key': '字符串字段', 'param_type': 'String', 'value': {'param_type': 'String', 'value': '示例字符串'}},
           {'key': '阵营字段', 'param_type': 'Camp', 'value': {'param_type': 'Camp', 'value': '022'}},
           {'key': '三维向量字段', 'param_type': 'Vector3', 'value': {'param_type': 'Vector3', 'value': '0,0,0'}},
           {'key': '元件ID字段', 'param_type': 'ComponentId', 'value': {'param_type': 'ComponentId', 'value': '0'}},
           {'key': '配置ID字段', 'param_type': 'ConfigId', 'value': {'param_type': 'ConfigId', 'value': '0'}},
           {'key': '结构体字段',
            'param_type': 'Struct',
            'value': {'param_type': 'Struct', 'value': {'structId': '', 'type': 'Struct', 'value': []}}},
           {'key': '字典字段',
            'param_type': 'Dict',
            'value': {'param_type': 'Dict',
                      'value': {'type': 'Dict',
                                'key_type': 'String',
                                'value_type': 'String',
                                'value': [{'key': {'param_type': 'String', 'value': '示例键111'},
                                           'value': {'param_type': 'String', 'value': '示例值11'}},
                                          {'key': {'param_type': 'String', 'value': '123123122'},
                                           'value': {'param_type': 'String', 'value': '213212'}}]}}},
           {'key': '实体列表字段',
            'param_type': 'EntityList',
            'value': {'param_type': 'EntityList', 'value': ['0', '123', '123', '123', '123123', '12']}},
           {'key': 'GUID列表字段',
            'param_type': 'GuidList',
            'value': {'param_type': 'GuidList',
                      'value': ['00000000-0000-0000-0000-000000000001',
                                '00000000-0000-0000-0000-000000000002',
                                '',
                                '']}},
           {'key': '整数列表字段', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': ['1', '2', '3']}},
           {'key': '布尔值列表字段',
            'param_type': 'BoolList',
            'value': {'param_type': 'BoolList', 'value': ['True', 'False']}},
           {'key': '浮点数列表字段', 'param_type': 'FloatList', 'value': {'param_type': 'FloatList', 'value': ['1.0', '2.5']}},
           {'key': '字符串列表字段',
            'param_type': 'StringList',
            'value': {'param_type': 'StringList', 'value': ['条目1', '条目2', '条目3']}},
           {'key': '阵营列表字段', 'param_type': 'CampList', 'value': {'param_type': 'CampList', 'value': ['0', '1']}},
           {'key': '三维向量列表字段',
            'param_type': 'Vector3List',
            'value': {'param_type': 'Vector3List', 'value': ['0,0,0', '1,2,3']}},
           {'key': '元件ID列表字段',
            'param_type': 'ComponentIdList',
            'value': {'param_type': 'ComponentIdList', 'value': ['0', '1']}},
           {'key': '配置ID列表字段',
            'param_type': 'ConfigIdList',
            'value': {'param_type': 'ConfigIdList', 'value': ['0', '1']}},
           {'key': '结构体列表字段',
            'param_type': 'StructList',
            'value': {'param_type': 'StructList', 'value': {'structId': '', 'value': []}}}]}
