from __future__ import annotations

# 仅用于类型检查工具（如 Pyright/Pylance）识别的“占位类型定义”。
# 运行时无任何行为，仅提供名称以避免“未定义类型”提示。
# 节点图验证仍以 runtime/node_graph_validator.py 的注解解析为准。

class 实体: ...
class GUID: ...
class 整数: ...
class 布尔值: ...
class 浮点数: ...
class 字符串: ...
class 三维向量: ...
class 元件ID: ...
class 配置ID: ...
class 字典: ...
class 结构体: ...
class 结构体: ...

class 实体列表: ...
class GUID列表: ...
class 整数列表: ...
class 布尔值列表: ...
class 浮点数列表: ...
class 字符串列表: ...
class 三维向量列表: ...
class 元件ID列表: ...
class 配置ID列表: ...
class 结构体列表: ...
class 结构体列表: ...

# 通用标记（一般不用于变量注解，仅作为端口类型存在）
class 通用: ...
class 泛型: ...


