from __future__ import annotations

from engine.resources.auto_custom_variable_registry import (
    AutoCustomVariableDeclaration,
)

# 本文件：自定义变量“统一声明入口”（不直接参与 Schema 加载）。
#
# 使用方式：
# - 运行（仅示例包）：
#   python -X utf8 -m app.cli.graph_tools sync-custom-vars --package-id 测试项目
#
# 说明：
# - owner：直接填实体/元件 ID 或 player/level（支持列表形式的多 owner）。
#
# 注意：
# - 不要在此文件编写运行期逻辑；仅做静态声明。
# - 字典变量 default_value 遵循“一层键值表”约束；不要写嵌套 dict（校验会失败）。

CUSTOM_VARIABLE_DECLARATIONS: list[AutoCustomVariableDeclaration] = [
    # ======================================================================
    # 玩家变量（每玩家独立，存放在“玩家模板/玩家实体”）
    # ======================================================================
    AutoCustomVariableDeclaration(
        variable_id="var_player_ui_button_equip_config_id",
        variable_name="UI_交互按钮_装备配置ID",
        variable_type="配置ID",
        default_value=0,
        description="UI 可交互按钮锚点的统一配置ID占位变量（所有按钮共用，默认 0）。",
        owner="player",
        category="UI",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_32d68a1b__测试项目",
        variable_name="test_string",
        variable_type="字符串",
        default_value="hello",
        description="由 UI 网页 data-ui-variable-defaults 导入（默认值来源于页面）。",
        owner="player",
        category="UI/网页默认值",
        metadata={"sources": ["管理配置/UI源码/ceshi_rect.html"]},
    ),
    # ---------------------------- 第七关：玩家侧通用 UI/流程变量 ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_ui_sel_level__测试项目",
        variable_name="ui_sel_level",
        variable_type="整数",
        default_value=0,
        description="玩家变量：当前选中的关卡号（选关页高亮/投票目标）。",
        owner="player",
        category="第七关/玩家",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_vote_level__测试项目",
        variable_name="ui_vote_level",
        variable_type="整数",
        default_value=0,
        description="玩家变量：进入关卡投票（0=未投票；>0=投票关卡号）。",
        owner="player",
        category="第七关/玩家",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_vote_settle__测试项目",
        variable_name="ui_vote_settle",
        variable_type="整数",
        default_value=0,
        description="玩家变量：结算投票（0=未投票；1=已投票）。",
        owner="player",
        category="第七关/玩家",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_player_index__测试项目",
        variable_name="ui_player_index",
        variable_type="整数",
        default_value=0,
        description="玩家变量：在场玩家序号（大厅前往选关时写入，用于后续映射站位/展示位）。",
        owner="player",
        category="第七关/玩家",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_tut_step__测试项目",
        variable_name="ui_tut_step",
        variable_type="整数",
        default_value=0,
        description="玩家变量：新手教程当前步（用于多态遮罩推进）。",
        owner="player",
        category="第七关/玩家",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_tut_done__测试项目",
        variable_name="ui_tut_done",
        variable_type="整数",
        default_value=0,
        description="玩家变量：新手教程完成标记（0/1）。",
        owner="player",
        category="第七关/玩家",
    ),
    # ---------------------------- 第七关：玩家侧选关预览（保存 GUID 而非实体引用） ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_ui_preview_level__测试项目",
        variable_name="ui_preview_level",
        variable_type="整数",
        default_value=0,
        description="玩家变量：当前预览关卡号（0=无预览）。",
        owner="player",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_preview_entity_1__测试项目",
        variable_name="ui_preview_entity_1",
        variable_type="实体",
        default_value=0,
        description="玩家变量：预览元件实体引用（第 1 个）。注意：创建元件生成的运行时实体通常没有可用 GUID，因此这里用实体引用承载清理。",
        owner="player",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_preview_entity_2__测试项目",
        variable_name="ui_preview_entity_2",
        variable_type="实体",
        default_value=0,
        description="玩家变量：预览元件实体引用（第 2 个；双元件关卡用）。注意：创建元件生成的运行时实体通常没有可用 GUID，因此这里用实体引用承载清理。",
        owner="player",
        category="第七关/选关预览",
    ),
    # ---------------------------- 第七关：玩家侧对局压岁钱/积分/选择 ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_money__测试项目",
        variable_name="ui_battle_money",
        variable_type="整数",
        default_value=0,
        description="玩家变量：压岁钱（顶栏 HUD / 结算榜单 money）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_score__测试项目",
        variable_name="ui_battle_score",
        variable_type="整数",
        default_value=0,
        description="玩家变量：积分（用于审判庭/排名/结算榜单 points）。按结算规则由关卡实体写回。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_rank__测试项目",
        variable_name="ui_battle_rank",
        variable_type="整数",
        default_value=1,
        description="玩家变量：当前排名（1=第一名）。用于顶栏个人 HUD 展示。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_integrity__测试项目",
        variable_name="ui_battle_integrity",
        variable_type="整数",
        default_value=100,
        description="玩家变量：年夜饭完整度（顶栏 HUD 展示；由关卡实体统计同步写回）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_i_min__测试项目",
        variable_name="ui_battle_i_min",
        variable_type="整数",
        default_value=0,
        description="玩家变量：年夜饭完整度进度条最小值（真实进度条 min 绑定；默认 0）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_i_max__测试项目",
        variable_name="ui_battle_i_max",
        variable_type="整数",
        default_value=100,
        description="玩家变量：年夜饭完整度进度条最大值（真实进度条 max 绑定；默认 100）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_integrityd__测试项目",
        variable_name="ui_battle_integrityd",
        variable_type="整数",
        default_value=0,
        description="玩家变量：本回合年夜饭完整度变化值（<=0；用于揭晓面板展示）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_survival__测试项目",
        variable_name="ui_battle_survival",
        variable_type="整数",
        default_value=10,
        description="玩家变量：手办存活数（顶栏 HUD 展示；0~10；由结算逻辑按个人错误写回）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_s_min__测试项目",
        variable_name="ui_battle_s_min",
        variable_type="整数",
        default_value=0,
        description="玩家变量：手办存活进度条最小值（真实进度条 min 绑定；默认 0）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_s_max__测试项目",
        variable_name="ui_battle_s_max",
        variable_type="整数",
        default_value=10,
        description="玩家变量：手办存活进度条最大值（真实进度条 max 绑定；默认 10）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_survivald__测试项目",
        variable_name="ui_battle_survivald",
        variable_type="整数",
        default_value=0,
        description="玩家变量：本回合手办存活变化值（<=0；用于揭晓面板展示）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_moneyd__测试项目",
        variable_name="ui_battle_moneyd",
        variable_type="整数",
        default_value=0,
        description="玩家变量：本回合压岁钱变化值（可正可负；用于揭晓面板展示）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_scored__测试项目",
        variable_name="ui_battle_scored",
        variable_type="整数",
        default_value=0,
        description="玩家变量：本回合积分变化值（可正可负；用于揭晓面板展示）。",
        owner="player",
        category="第七关/对局",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_battle_choice__测试项目",
        variable_name="ui_battle_choice",
        variable_type="整数",
        default_value=0,
        description="玩家变量：本回合选择（0=未选；1=允许；2=拒绝）。",
        owner="player",
        category="第七关/对局",
    ),
    # ---------------------------- 第七关：结算页左栏评语/状态（每玩家独立） ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_ui_settle_i_st__测试项目",
        variable_name="ui_settle_i_st",
        variable_type="字符串",
        default_value=" ",
        description="玩家变量：结算页『年夜饭完整度』状态文案（每玩家独立）。",
        owner="player",
        category="第七关/结算",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_settle_s_st__测试项目",
        variable_name="ui_settle_s_st",
        variable_type="字符串",
        default_value=" ",
        description="玩家变量：结算页『手办存活数』状态文案（每玩家独立）。",
        owner="player",
        category="第七关/结算",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_settle_ev1__测试项目",
        variable_name="ui_settle_ev1",
        variable_type="字符串",
        default_value=" ",
        description="玩家变量：结算页评语第 1 行（每玩家独立）。",
        owner="player",
        category="第七关/结算",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_settle_ev2__测试项目",
        variable_name="ui_settle_ev2",
        variable_type="字符串",
        default_value=" ",
        description="玩家变量：结算页评语第 2 行（每玩家独立）。",
        owner="player",
        category="第七关/结算",
    ),

    # ======================================================================
    # 关卡实体变量（全局共享，存放在“关卡实体/关卡实体实例”）
    # ======================================================================
    AutoCustomVariableDeclaration(
        variable_id="ui_ff71291c__测试项目",
        variable_name="UI_装饰进度条_最大值",
        variable_type="整数",
        default_value=100,
        description="由 UI 网页 data-ui-variable-defaults 导入（默认值来源于页面）。",
        owner="level",
        category="UI/网页默认值",
        metadata={"sources": ["管理配置/UI源码/ceshi_rect.html"]},
    ),
    # ---------------------------- 选关预览配置（由主图写入，关卡实体图读取执行） ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_ui_level_select_preview_cfg_comp1__测试项目",
        variable_name="UI选关_预览_展示元件ID_1",
        variable_type="元件ID列表",
        default_value=[],
        description="关卡实体变量：预览展示元件（第 1 个）元件ID 查表（列表长度=10；序号=关卡号-1）。",
        owner="level",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_level_select_preview_cfg_comp2__测试项目",
        variable_name="UI选关_预览_展示元件ID_2",
        variable_type="元件ID列表",
        default_value=[],
        description="关卡实体变量：预览展示元件（第 2 个）元件ID 查表（列表长度=10；序号=关卡号-1；双元件关卡用）。",
        owner="level",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_level_select_preview_cfg_offset__测试项目",
        variable_name="UI选关_预览配置_关卡号到展示位置偏移",
        variable_type="三维向量列表",
        default_value=[],
        description="关卡实体变量：预览元件相对“展示位置”的额外位置偏移查表（三维向量列表；长度=10；序号=关卡号-1）。",
        owner="level",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_level_select_preview_cfg_offset2__测试项目",
        variable_name="UI选关_预览_第二元件偏移",
        variable_type="三维向量列表",
        default_value=[],
        description="关卡实体变量：双元件关卡第 2 个元件相对第 1 个的自带偏移查表（三维向量列表；长度=10；序号=关卡号-1）。",
        owner="level",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_level_select_preview_cfg_rot1__测试项目",
        variable_name="UI选关_预览配置_关卡号到展示旋转_1",
        variable_type="三维向量列表",
        default_value=[],
        description="关卡实体变量：预览展示元件（第 1 个）旋转查表（三维向量列表；长度=10；序号=关卡号-1）。",
        owner="level",
        category="第七关/选关预览",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_ui_level_select_preview_cfg_rot2__测试项目",
        variable_name="UI选关_预览配置_关卡号到展示旋转_2",
        variable_type="三维向量列表",
        default_value=[],
        description="关卡实体变量：预览展示元件（第 2 个）旋转查表（三维向量列表；长度=10；序号=关卡号-1）。",
        owner="level",
        category="第七关/选关预览",
    ),
    # ---------------------------- 选关投票倒计时锁（跨图共享） ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_level_select_vote_countdown_running__测试项目",
        variable_name="选关_投票倒计时_进行中",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：选关投票倒计时是否进行中（0/1）。用于跨图锁定倒计时末端逻辑。",
        owner="level",
        category="第七关/选关投票",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level_select_vote_countdown_mode__测试项目",
        variable_name="选关_投票倒计时_模式",
        variable_type="字符串",
        default_value="无",
        description="关卡实体变量：选关投票倒计时模式（enter_level / settle / 无）。",
        owner="level",
        category="第七关/选关投票",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level_select_vote_countdown_target_level__测试项目",
        variable_name="选关_投票倒计时_目标关卡",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：选关投票倒计时锁定的目标关卡号（enter_level 模式使用）。",
        owner="level",
        category="第七关/选关投票",
    ),
    # ---------------------------- 门后流程与亲戚实体引用 ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_level7_door_post_action__测试项目",
        variable_name="第七关_门_关闭完成后待办",
        variable_type="字符串",
        default_value="无",
        description="关卡实体变量：门关闭完成后要执行的业务动作（字符串枚举；无/开局/下一回合/进入结算）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_relative_body_entity__测试项目",
        variable_name="第七关_亲戚_身体实体",
        variable_type="实体",
        default_value=0,
        description="关卡实体变量：当前亲戚身体部件实体引用（用于销毁/替换）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_relative_eye_entity__测试项目",
        variable_name="第七关_亲戚_眼睛实体",
        variable_type="实体",
        default_value=0,
        description="关卡实体变量：当前亲戚眼睛部件实体引用（用于销毁/替换）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_relative_hair_entity__测试项目",
        variable_name="第七关_亲戚_头发实体",
        variable_type="实体",
        default_value=0,
        description="关卡实体变量：当前亲戚头发部件实体引用（用于销毁/替换）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_relative_beard_entity__测试项目",
        variable_name="第七关_亲戚_胡子实体",
        variable_type="实体",
        default_value=0,
        description="关卡实体变量：当前亲戚胡子部件实体引用（用于销毁/替换）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_relative_neckwear_entity__测试项目",
        variable_name="第七关_亲戚_领带实体",
        variable_type="实体",
        default_value=0,
        description="关卡实体变量：当前亲戚领饰部件实体引用（用于销毁/替换）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_relative_clothes_entity__测试项目",
        variable_name="第七关_亲戚_衣服实体",
        variable_type="实体",
        default_value=0,
        description="关卡实体变量：当前亲戚衣服部件实体引用（用于销毁/替换）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    # ---------------------------- 本回合真相与结算/推进触发数据 ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_truth_allow__测试项目",
        variable_name="第七关_本回合_真相为允许",
        variable_type="布尔值",
        default_value=False,
        description="关卡实体变量：本回合真相（True=允许，False=拒绝）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_is_child__测试项目",
        variable_name="第七关_本回合_是否小孩",
        variable_type="布尔值",
        default_value=False,
        description="关卡实体变量：本回合是否为“小孩”来访者（用于扣手办逻辑）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_relative_title__测试项目",
        variable_name="第七关_本回合_亲戚称谓",
        variable_type="字符串",
        default_value="",
        description="关卡实体变量：本回合来访者称谓（由数据服务下发，用于跨图共享与 UI 展示）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_settlement_trigger_mark__测试项目",
        variable_name="第七关_结算触发_标记",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：结算派发触发标记（玩家侧写入，关卡实体结算图读取）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_settlement_trigger_allow_votes__测试项目",
        variable_name="第七关_结算触发_允许票",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：结算派发时的允许票数（玩家侧汇总写入）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_settlement_trigger_reject_votes__测试项目",
        variable_name="第七关_结算触发_拒绝票",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：结算派发时的拒绝票数（玩家侧汇总写入）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_advance_trigger_mark__测试项目",
        variable_name="第七关_回合推进触发_标记",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：回合推进派发触发标记（玩家侧写入，关卡实体推进图读取）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_advance_trigger_is_last__测试项目",
        variable_name="第七关_回合推进触发_是否最后回合",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：回合推进派发是否最后回合（0/1）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    # ---------------------------- 跨图共享状态（阶段/回合/对白缓存） ----------------------------
    AutoCustomVariableDeclaration(
        variable_id="var_level7_stage__测试项目",
        variable_name="第七关_当前阶段",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：比赛阶段（0=新手教学等待开局；1=进场；2=投票；3=结算）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_inited__测试项目",
        variable_name="第七关_已初始化",
        variable_type="布尔值",
        default_value=False,
        description="关卡实体变量：公共控制图一次性初始化守护（False/True）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_has_broadcast_start__测试项目",
        variable_name="第七关_已广播开局信号",
        variable_type="布尔值",
        default_value=False,
        description="关卡实体变量：是否已广播『第七关_开始游戏』信号（去重用）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_index__测试项目",
        variable_name="第七关_当前回合序号",
        variable_type="整数",
        default_value=1,
        description="关卡实体变量：当前回合序号（1~总回合数）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_dialogue_lines__测试项目",
        variable_name="第七关_本回合_对白列表",
        variable_type="字符串列表",
        default_value=[" "],
        description="关卡实体变量：本回合对白列表缓存（供『对话』按钮循环展示）。",
        owner="level",
        category="第七关/关卡实体",
    ),
    AutoCustomVariableDeclaration(
        variable_id="var_level7_round_dialogue_index__测试项目",
        variable_name="第七关_本回合_对白序号",
        variable_type="整数",
        default_value=0,
        description="关卡实体变量：本回合对白序号（对话按钮递增，超出则回绕）。",
        owner="level",
        category="第七关/关卡实体",
    ),

    # ======================================================================
    # UI 字典变量（原 UI_关卡变量_自动生成.py 真源迁入；单文件真源：注册表）
    # ======================================================================
    AutoCustomVariableDeclaration(
        variable_id="ui_3c2550c5__测试项目",
        variable_name="UI战斗_揭晓",
        variable_type="字符串-字符串字典",
        default_value={
            "揭晓标题": "审判结果揭晓",
            "揭晓副标题": "本轮目标：二舅",
            "徽章_等待": "等待投票",
            "徽章_揭晓": "揭晓中",
            "徽章_允许": "允许进入",
            "徽章_拒绝": "拒绝进入",
            "结果等待_标题": "等待所有玩家选择完毕…",
            "结果等待_述": "有人还在犹豫。等他们做出决定，我们就揭晓结果。",
            "结果揭晓_标题": "正在揭晓…",
            "结果揭晓_述": "结果马上公布！",
            "结果允许_标题": "允许进入！",
            "结果允许_述": "你们判断正确：这位亲戚没有问题。",
            "结果拒绝_标题": "拒绝进入！",
            "结果拒绝_述": "你们判断失误：他其实是年兽伪装。",
            "变化_压岁钱_标题": "压岁钱",
            "变化_压岁钱": "+0",
            "变化_完整度_标题": "年夜饭完整度",
            "变化_完整度": "-5",
            "变化_得分_标题": "得分",
            "变化_得分": "+0",
            "变化_存活_标题": "手办存活",
            "变化_存活": "0",
            "按钮_继续": "继续下一位",
            "按钮_关闭": "继续",
            "徽章_结果": "结果",
            "结果_判定": "判断正确",
            "结果_描述": "这位亲戚是真的。",
            "结果_真相": "真亲戚",
        },
        description="UI 页面 data-ui-variable-defaults 默认值（由 apply-ui-defaults --all 自动同步）",
        owner="level",
        category="UI/战斗",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_8eb9b141__测试项目",
        variable_name="UI战斗_整数",
        variable_type="字符串-整数字典",
        default_value={"新手教程_剩余秒": 30, "新手教程_已完成人数": 1, "新手教程_总人数": 4},
        description="UI 文本占位符引用（由 validate-ui 校验；真源在注册表）。",
        owner="level",
        category="UI/战斗",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_78afce52__测试项目",
        variable_name="UI战斗_文本",
        variable_type="字符串-字符串字典",
        default_value={
            "压岁钱": "¥ 600",
            "完整度": "80",
            "存活": "3 / 5",
            "排名": "No. 2",
            "线索标题": "妈妈的纸条",
            "线索1标": "表舅",
            "线索1文": "飞机头戴眼镜",
            "线索2标": "堂嫂",
            "线索2文": "普通发小胡茬",
            "线索3标": "舅爷爷",
            "线索3文": "大背头配领带",
            "线索4标": "姥姥",
            "线索4文": "不戴眼镜无胡子",
            "线索5标": "姑父",
            "线索5文": "马尾胸前铃铛",
            "线索6标": "伯母",
            "线索6文": "墨镜长胡子",
            "审判标题": "亲戚审判庭",
            "审判1名": "我",
            "审判1分": "600分",
            "审判1态": "思考中",
            "审判2名": "表弟",
            "审判2分": "820分",
            "审判2态": "允许",
            "审判3名": "堂姐",
            "审判3分": "1010分",
            "审判3态": "拒绝",
            "审判4名": "路人",
            "审判4分": "200分",
            "审判4态": "思考中",
            "回合倒计时": "08",
            "对话": "给你带了个大红包。",
            "指引1_标题": "先看资源条",
            "指引1_正文": "我们的目标：尽可能多拿压岁钱，同时保住年夜饭完整度和手办存活。",
            "指引1_步骤": "指引 1/6",
            "指引2_标题": "先看纸条线索",
            "指引2_正文": "妈妈的纸条是你最可靠的线索来源。",
            "指引2_步骤": "指引 2/6",
            "指引3_标题": "观察中间展示区",
            "指引3_正文": "中间是现场展示区：你需要观察外貌细节，并和纸条对照。",
            "指引3_步骤": "指引 3/6",
            "指引4_标题": "先点击对话",
            "指引4_正文": "不确定就先问一句：点“对话”获取更多信息。",
            "指引4_步骤": "指引 4/6",
            "指引5_标题": "阅读亲戚对白",
            "指引5_正文": "对白会提供关键线索：不要轻易相信他的话。",
            "指引5_步骤": "指引 5/6",
            "指引6_标题": "最后再做决定",
            "指引6_正文": "千万只允许真的亲戚进入哦。",
            "指引6_步骤": "指引 6/6",
            "指引_按钮_下一步": "下一步",
            "指引_按钮_完成": "完成",
            "指引完成_标题": "可以开始了",
            "指引完成_正文": "祝你多拿压岁钱，守住年夜饭！",
            "指引完成_步骤": "指引完成",
            "新手教程_倒计时_单位": "秒",
            "新手教程_倒计时_标题": "新手教学倒计时",
            "新手教程_等待_副标题_前": "当前已完成 ",
            "新手教程_等待_副标题_后": " 人",
            "新手教程_等待_标题": "已完成新手教学，等待其他玩家…",
            "指引0_标题": "年关将至",
            "指引0_正文": "新年快到了。妈妈临时有事出门，拜托你在家招待来访的亲戚。可你总觉得哪里不对……他们真的是你的亲戚吗？",
            "指引0_步骤": "背景故事",
        },
        description="UI 页面 data-ui-variable-defaults 默认值（由 apply-ui-defaults --all 自动同步）",
        owner="level",
        category="UI/战斗",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_0b8ff1a8__测试项目",
        variable_name="UI战斗_颜色",
        variable_type="字符串-字符串字典",
        default_value={"审判1态": "#000000", "审判2态": "#577718", "审判3态": "#c92a2a", "审判4态": "#000000"},
        description="UI 文本占位符引用（由 validate-ui 校验；真源在注册表）。",
        owner="level",
        category="UI/战斗",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_1c5b3d8a__测试项目",
        variable_name="UI房间_文本",
        variable_type="字符串-字符串字典",
        default_value={"房名": "", "倒计时_长": "距离新年钟声还有 00:00", "倒计时": "00:00", "玩家列表标题": "玩家列表", "模式标题": "模式选择", "玩家1名": "我（房主）", "玩家2名": "表弟阿强", "玩家3名": "二姑父", "玩家4名": "等待加入", "空位提示": "空位", "状态_已准备": "已准备", "状态_思考中": "思考中", "状态_未就绪": "未就绪", "模式1名": "新手教程", "模式1述": "建议初次游玩者选择，包含识人辨马基础教学。", "模式2名": "正式开席", "模式2述": "直接开始高强度除夕守卫战，节奏更紧凑。", "自动开局提示_前": "提示：任一选项获得 ", "自动开局提示_后": " 票将直接开始。", "按钮_退出房间": "退出房间", "按钮_开始": "开始游戏", "当前投票_前": "", "当前投票_无": "", "我的投票": "", "按钮_已投票": "已投票", "按钮_投票": "投票此模式", "倒计时_分": "03", "倒计时_秒": "20", "剩余亲戚_当前": "10", "剩余亲戚_总": "10"},
        description="UI 页面 data-ui-variable-defaults 默认值（由 apply-ui-defaults --all 自动同步）",
        owner="level",
        category="UI/大厅",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_5360be1f__测试项目",
        variable_name="UI样式_颜色",
        variable_type="字符串-字符串字典",
        default_value={"状态_允许": "#577718", "状态_思考中": "#000000", "状态_拒绝": "#c92a2a"},
        description="UI 文本占位符引用（由 validate-ui 校验；真源在注册表）。",
        owner="level",
        category="UI/样式",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_bff3168a__测试项目",
        variable_name="UI结算_文本",
        variable_type="字符串-字符串字典",
        default_value={
            "标题": "除夕夜结算报告",
            "左栏标题": "家庭财产损耗",
            "完整度_标题": "年夜饭完整度",
            "完整度_状态": "严重受损",
            "完整度_文本": "20%",
            "手办_标题": "手办存活数",
            "手办_状态": "全军覆没",
            "手办_文本": "0 / 10",
            "评语1": "这年过得太惨了，菜被偷吃光，手办全阵亡。",
            "评语2": "妈正拿着鸡毛掸子赶来，预计到达时间：10 秒。",
            "右栏标题": "守岁英雄榜",
            "榜1名次": "1",
            "榜1名": "大表哥（我）",
            "榜1标签": "识别准确率：92% | MVP",
            "榜1钱": "¥ 2,400",
            "榜1分": "150 积分",
            "榜2名次": "2",
            "榜2名": "彩虹小马",
            "榜2标签": "误放熊孩子：2 次",
            "榜2钱": "¥ 1,100",
            "榜2分": "90 积分",
            "榜3名次": "3",
            "榜3名": "条纹杀手",
            "榜3标签": "把二舅赶走了（大不敬）",
            "榜3钱": "¥ -200",
            "榜3分": "40 积分",
            "榜4名次": "4",
            "榜4名": "眼神不佳",
            "榜4标签": "全程挂机",
            "榜4钱": "¥ -800",
            "榜4分": "0 积分",
            "按钮_返回": "返回大厅",
            "按钮_重开": "再来一年",
            "榜1分后缀": " 积分",
            "榜1钱前缀": "¥ ",
            "榜2分后缀": " 积分",
            "榜2钱前缀": "¥ ",
            "榜3分后缀": " 积分",
            "榜3钱前缀": "¥ ",
            "榜4分后缀": " 积分",
            "榜4钱前缀": "¥ ",
        },
        description="UI 页面 data-ui-variable-defaults 默认值（由 apply-ui-defaults --all 自动同步）",
        owner="level",
        category="UI/结算",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_ab599971__测试项目",
        variable_name="UI选关_列表",
        variable_type="字符串-字符串字典",
        default_value={
            "cleared_count": 0,
            "level_01_cleared": 0,
            "level_02_cleared": 0,
            "level_03_cleared": 0,
            "level_04_cleared": 0,
            "level_05_cleared": 0,
            "level_06_cleared": 0,
            "level_07_cleared": 0,
            "level_08_cleared": 0,
            "level_09_cleared": 0,
            "level_10_cleared": 0,
            "lv01_online_cnt": 0,
            "lv02_online_cnt": 0,
            "lv03_online_cnt": 0,
            "lv04_online_cnt": 0,
            "lv05_online_cnt": 0,
            "lv06_online_cnt": 0,
            "lv07_online_cnt": 0,
            "lv08_online_cnt": 0,
            "lv09_online_cnt": 0,
            "lv10_online_cnt": 0,
        },
        description="UI 占位符与状态切换键（由 validate-ui/apply-ui-defaults 补齐；含节点图依赖键）。",
        owner="level",
        category="UI/选关",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_71c33269__测试项目",
        variable_name="UI选关_投票",
        variable_type="字符串-字符串字典",
        default_value={
            "total_players": "1",
            "voted_players": "0",
            "majority_needed": "0",
            "chosen_level_name": "第一关",
            "countdown_sec": "5",
            "vote_cancel_rejecter_name": "某位玩家",
            "countdown_label": "进入关卡倒计时",
            "vote_mode": "enter_level",
        },
        description="UI 页面 data-ui-variable-defaults 默认值（由 extract/apply-ui-defaults 自动同步）",
        owner="level",
        category="UI/选关",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_105810ca__测试项目",
        variable_name="UI选关_文本",
        variable_type="字符串-字符串字典",
        default_value={
            "author_name": "兔崽子你真的完蛋了",
            "level_01_author_name": "兔崽子你真的完蛋了",
            "level_01_name": "第一关",
            "level_02_author_name": "必杀生火人",
            "level_02_name": "第二关",
            "level_03_author_name": "火山哥哥",
            "level_03_name": "第三关",
            "level_04_author_name": "Apple 苹果酱喔",
            "level_04_name": "第四关",
            "level_05_author_name": "蚊香长老",
            "level_05_name": "第五关",
            "level_06_author_name": "M木糖M",
            "level_06_name": "第六关",
            "level_07_author_name": "Ayaya小王",
            "level_07_name": "第七关",
            "level_08_author_name": "披荆斩棘的张总",
            "level_08_name": "第八关",
            "level_09_author_name": "小问号Official",
            "level_09_name": "第九关",
            "level_10_author_name": "特效小哥",
            "level_10_name": "第十关",
            "level_name": "第一关",
            "settle_tip_status": "您还需要完成 3 关以进行结算",
        },
        description="UI 文本占位符引用（由 validate-ui 校验；真源在注册表）。",
        owner="level",
        category="UI/选关",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_9083fcfe__测试项目",
        variable_name="UI选关_结算提示",
        variable_type="字符串-整数字典",
        default_value={"required_cleared_count": 3, "remaining_cleared_count": 3, "auto_hide_ms": 2500},
        description="UI 页面 data-ui-variable-defaults 默认值（由 extract/apply-ui-defaults 自动同步）",
        owner="level",
        category="UI/选关",
    ),
    AutoCustomVariableDeclaration(
        variable_id="ui_362cc6fa__测试项目",
        variable_name="UI选关_预览_展示位GUID",
        variable_type="字符串",
        default_value="",
        description="UI 文本占位符引用（由 validate-ui 校验；真源在注册表）。",
        owner="level",
        category="UI/选关预览",
    ),
]

