from __future__ import annotations

from engine.graph.models.package_model import LevelVariableDefinition

VARIABLE_FILE_ID = "test_project_level7_relatives_data_store_vars__测试项目"
VARIABLE_FILE_NAME = "测试项目_第七关_亲戚数据存放变量"

# 说明：
# - 第七关“真假亲戚”round 库数据存放实体所用的自定义变量键（variable_name）在此集中声明；
# - 节点图中【获取自定义变量/设置自定义变量】会对 variable_name 做严格校验，必须存在于当前存档引用的关卡变量集合中；
# - 真实的大体量默认值存放在数据存放元件模板的“自定义变量组件”里；这里仅提供类型与最小默认结构（0 / 空列表）。
LEVEL_VARIABLES: list[LevelVariableDefinition] = [
    LevelVariableDefinition(
        variable_id="l7_rel_rounds_count__测试项目",
        variable_name="l7_rounds_count",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="第七关亲戚 round 库：总局数（数据存放实体自定义变量）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_clue_title__测试项目",
        variable_name="l7_clue_title",
        variable_type="字符串",
        default_value="妈妈的纸条",
        is_global=False,
        description="第七关妈妈纸条标题（数据存放实体自定义变量）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_clue_tags_flat__测试项目",
        variable_name="l7_clue_tags_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关妈妈纸条标签扁平列表：长度=rounds_count*6。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_clue_texts_flat__测试项目",
        variable_name="l7_clue_texts_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关妈妈纸条文本扁平列表：长度=rounds_count*6。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_role_flat__测试项目",
        variable_name="l7_visit_role_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访称谓扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_truth_allow_flat__测试项目",
        variable_name="l7_visit_truth_flat",
        variable_type="布尔值列表",
        default_value=[],
        is_global=False,
        description="第七关来访真相（是否允许）扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_body_flat__测试项目",
        variable_name="l7_visit_body_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访外观_身体扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_hair_flat__测试项目",
        variable_name="l7_visit_hair_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访外观_头发扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_beard_flat__测试项目",
        variable_name="l7_visit_beard_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访外观_胡子扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_glasses_flat__测试项目",
        variable_name="l7_visit_glass_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访外观_眼镜扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_clothes_flat__测试项目",
        variable_name="l7_visit_cloth_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访外观_衣服扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_neckwear_flat__测试项目",
        variable_name="l7_visit_neck_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访外观_领饰扁平列表：长度=rounds_count*10。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_dialogue_l1_flat__测试项目",
        variable_name="l7_visit_dlg_l1_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访对白扁平列表（第1句）：长度=rounds_count*10（每项已带称谓前缀）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_dialogue_l2_flat__测试项目",
        variable_name="l7_visit_dlg_l2_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访对白扁平列表（第2句）：长度=rounds_count*10（每项已带称谓前缀）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_dialogue_l3_flat__测试项目",
        variable_name="l7_visit_dlg_l3_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访对白扁平列表（第3句）：长度=rounds_count*10（每项已带称谓前缀）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_dialogue_l4_flat__测试项目",
        variable_name="l7_visit_dlg_l4_flat",
        variable_type="字符串列表",
        default_value=[],
        is_global=False,
        description="第七关来访对白扁平列表（第4句）：长度=rounds_count*10（每项已带称谓前缀）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_selected_round_index__测试项目",
        variable_name="l7_sel_round_idx",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="第七关本局选中 round 序号（运行态指针）。",
        metadata={"category": "第七关"},
    ),
    LevelVariableDefinition(
        variable_id="l7_rel_visit_i__测试项目",
        variable_name="l7_visit_i",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="第七关当前来访序号 0~9（运行态指针）。",
        metadata={"category": "第七关"},
    ),
]

