from __future__ import annotations

from engine.graph.models.package_model import LevelVariableDefinition

VARIABLE_FILE_ID = "test_project_level7_runtime_vars__测试项目"
VARIABLE_FILE_NAME = "测试项目_第七关_流程运行变量"

# 说明：
# - 本文件集中声明“第七关闭环运行期”会读写的自定义变量（variable_name）；
# - 这些变量会被玩家侧 UI 图与关卡实体侧流程图通过【获取自定义变量/设置自定义变量】访问；
# - 这里只提供类型与最小默认值（0 / 空字典 / 空字符串等），具体运行期写入由节点图负责。
LEVEL_VARIABLES: list[LevelVariableDefinition] = [
    # ---------------------------- 玩家侧：通用 UI/流程变量 ----------------------------
    LevelVariableDefinition(
        variable_id="var_ui_sel_level__测试项目",
        variable_name="ui_sel_level",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：当前选中的关卡号（选关页高亮/投票目标）。",
        metadata={"category": "第七关/玩家"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_vote_level__测试项目",
        variable_name="ui_vote_level",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：进入关卡投票（0=未投票；>0=投票关卡号）。",
        metadata={"category": "第七关/玩家"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_vote_settle__测试项目",
        variable_name="ui_vote_settle",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：结算投票（0=未投票；1=已投票）。",
        metadata={"category": "第七关/玩家"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_player_index__测试项目",
        variable_name="ui_player_index",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：在场玩家序号（大厅前往选关时写入，用于后续映射站位/展示位）。",
        metadata={"category": "第七关/玩家"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_tut_step__测试项目",
        variable_name="ui_tut_step",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：新手教程当前步（用于多态遮罩推进）。",
        metadata={"category": "第七关/玩家"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_tut_done__测试项目",
        variable_name="ui_tut_done",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：新手教程完成标记（0/1）。",
        metadata={"category": "第七关/玩家"},
    ),
    # ---------------------------- 玩家侧：选关预览（保存 实体引用；创建元件通常没有可用 GUID） ----------------------------
    LevelVariableDefinition(
        variable_id="var_ui_preview_level__测试项目",
        variable_name="ui_preview_level",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：当前预览关卡号（0=无预览）。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_preview_entity_1__测试项目",
        variable_name="ui_preview_entity_1",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="玩家变量：预览元件实体引用（第 1 个）。注意：创建元件生成的运行时实体通常没有可用 GUID，因此这里用实体引用承载清理。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_preview_entity_2__测试项目",
        variable_name="ui_preview_entity_2",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="玩家变量：预览元件实体引用（第 2 个；双元件关卡用）。注意：创建元件生成的运行时实体通常没有可用 GUID，因此这里用实体引用承载清理。",
        metadata={"category": "第七关/选关预览"},
    ),
    # ---------------------------- 玩家侧：对局得分/选择 ----------------------------
    LevelVariableDefinition(
        variable_id="var_ui_battle_points__测试项目",
        variable_name="ui_battle_points",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：对局得分（审判庭/结算榜单使用）。",
        metadata={"category": "第七关/对局"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_battle_choice__测试项目",
        variable_name="ui_battle_choice",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="玩家变量：本回合选择（0=未选；1=允许；2=拒绝）。",
        metadata={"category": "第七关/对局"},
    ),
    # ---------------------------- 关卡实体侧：选关预览配置（由主图写入，本图读取执行） ----------------------------
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_anchor__测试项目",
        variable_name="UI选关_预览_展示位GUID",
        variable_type="整数-GUID字典",
        default_value={},
        is_global=False,
        description="关卡实体变量：玩家序号→预览展示锚点 GUID。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_comp1__测试项目",
        variable_name="UI选关_预览_展示元件ID_1",
        variable_type="元件ID列表",
        default_value=[],
        is_global=False,
        description="关卡实体变量：预览展示元件（第 1 个）元件ID 查表（列表长度=10；序号=关卡号-1）。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_comp2__测试项目",
        variable_name="UI选关_预览_展示元件ID_2",
        variable_type="元件ID列表",
        default_value=[],
        is_global=False,
        description="关卡实体变量：预览展示元件（第 2 个）元件ID 查表（列表长度=10；序号=关卡号-1；双元件关卡用）。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_offset__测试项目",
        variable_name="UI选关_预览配置_关卡号到展示位置偏移",
        variable_type="三维向量列表",
        default_value=[],
        is_global=False,
        description="关卡实体变量：预览元件相对“展示位置”的额外位置偏移查表（三维向量列表；长度=10；序号=关卡号-1）。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_offset2__测试项目",
        variable_name="UI选关_预览_第二元件偏移",
        variable_type="三维向量列表",
        default_value=[],
        is_global=False,
        description="关卡实体变量：双元件关卡第 2 个元件相对第 1 个的自带偏移查表（三维向量列表；长度=10；序号=关卡号-1）。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_rot1__测试项目",
        variable_name="UI选关_预览配置_关卡号到展示旋转_1",
        variable_type="三维向量列表",
        default_value=[],
        is_global=False,
        description="关卡实体变量：预览展示元件（第 1 个）旋转查表（三维向量列表；长度=10；序号=关卡号-1）。",
        metadata={"category": "第七关/选关预览"},
    ),
    LevelVariableDefinition(
        variable_id="var_ui_level_select_preview_cfg_rot2__测试项目",
        variable_name="UI选关_预览配置_关卡号到展示旋转_2",
        variable_type="三维向量列表",
        default_value=[],
        is_global=False,
        description="关卡实体变量：预览展示元件（第 2 个）旋转查表（三维向量列表；长度=10；序号=关卡号-1）。",
        metadata={"category": "第七关/选关预览"},
    ),
    # ---------------------------- 关卡实体侧：选关投票倒计时锁（跨图共享） ----------------------------
    LevelVariableDefinition(
        variable_id="var_level_select_vote_countdown_running__测试项目",
        variable_name="选关_投票倒计时_进行中",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：选关投票倒计时是否进行中（0/1）。用于跨图锁定倒计时末端逻辑。",
        metadata={"category": "第七关/选关投票"},
    ),
    LevelVariableDefinition(
        variable_id="var_level_select_vote_countdown_mode__测试项目",
        variable_name="选关_投票倒计时_模式",
        variable_type="字符串",
        default_value="",
        is_global=False,
        description="关卡实体变量：选关投票倒计时模式（enter_level / settle）。",
        metadata={"category": "第七关/选关投票"},
    ),
    LevelVariableDefinition(
        variable_id="var_level_select_vote_countdown_target_level__测试项目",
        variable_name="选关_投票倒计时_目标关卡",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：选关投票倒计时锁定的目标关卡号（enter_level 模式使用）。",
        metadata={"category": "第七关/选关投票"},
    ),
    # ---------------------------- 关卡实体侧：门后流程与亲戚实体引用 ----------------------------
    LevelVariableDefinition(
        variable_id="var_level7_door_post_action__测试项目",
        variable_name="第七关_门_关闭完成后待办",
        variable_type="字符串",
        default_value="",
        is_global=False,
        description="关卡实体变量：门关闭完成后要执行的业务动作（字符串枚举）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_relative_body_entity__测试项目",
        variable_name="第七关_亲戚_身体实体",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="关卡实体变量：当前亲戚身体部件实体引用（用于销毁/替换）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_relative_eye_entity__测试项目",
        variable_name="第七关_亲戚_眼睛实体",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="关卡实体变量：当前亲戚眼睛部件实体引用（用于销毁/替换）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_relative_hair_entity__测试项目",
        variable_name="第七关_亲戚_头发实体",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="关卡实体变量：当前亲戚头发部件实体引用（用于销毁/替换）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_relative_beard_entity__测试项目",
        variable_name="第七关_亲戚_胡子实体",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="关卡实体变量：当前亲戚胡子部件实体引用（用于销毁/替换）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_relative_neckwear_entity__测试项目",
        variable_name="第七关_亲戚_领带实体",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="关卡实体变量：当前亲戚领饰部件实体引用（用于销毁/替换）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_relative_clothes_entity__测试项目",
        variable_name="第七关_亲戚_衣服实体",
        variable_type="实体",
        default_value=0,
        is_global=False,
        description="关卡实体变量：当前亲戚衣服部件实体引用（用于销毁/替换）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    # ---------------------------- 关卡实体侧：本回合真相与结算/推进触发数据 ----------------------------
    LevelVariableDefinition(
        variable_id="var_level7_round_truth_allow__测试项目",
        variable_name="第七关_本回合_真相为允许",
        variable_type="布尔值",
        default_value=False,
        is_global=False,
        description="关卡实体变量：本回合真相（True=允许，False=拒绝）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_is_child__测试项目",
        variable_name="第七关_本回合_是否小孩",
        variable_type="布尔值",
        default_value=False,
        is_global=False,
        description="关卡实体变量：本回合是否为“小孩”来访者（用于扣手办逻辑）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_relative_title__测试项目",
        variable_name="第七关_本回合_亲戚称谓",
        variable_type="字符串",
        default_value="",
        is_global=False,
        description="关卡实体变量：本回合来访者称谓（由数据服务下发，用于跨图共享与 UI 展示）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_settlement_trigger_mark__测试项目",
        variable_name="第七关_结算触发_标记",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：结算派发触发标记（玩家侧写入，关卡实体结算图读取）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_settlement_trigger_allow_votes__测试项目",
        variable_name="第七关_结算触发_允许票",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：结算派发时的允许票数（玩家侧汇总写入）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_settlement_trigger_reject_votes__测试项目",
        variable_name="第七关_结算触发_拒绝票",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：结算派发时的拒绝票数（玩家侧汇总写入）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_advance_trigger_mark__测试项目",
        variable_name="第七关_回合推进触发_标记",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：回合推进派发触发标记（玩家侧写入，关卡实体推进图读取）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_advance_trigger_is_last__测试项目",
        variable_name="第七关_回合推进触发_是否最后回合",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：回合推进派发是否最后回合（0/1）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    # ---------------------------- 关卡实体侧：跨图共享状态（阶段/回合/对白缓存） ----------------------------
    LevelVariableDefinition(
        variable_id="var_level7_stage__测试项目",
        variable_name="第七关_当前阶段",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：比赛阶段（0=新手教学等待开局；1=进场；2=投票；3=结算）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_inited__测试项目",
        variable_name="第七关_已初始化",
        variable_type="布尔值",
        default_value=False,
        is_global=False,
        description="关卡实体变量：公共控制图一次性初始化守护（False/True）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_has_broadcast_start__测试项目",
        variable_name="第七关_已广播开局信号",
        variable_type="布尔值",
        default_value=False,
        is_global=False,
        description="关卡实体变量：是否已广播『第七关_开始游戏』信号（去重用）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_index__测试项目",
        variable_name="第七关_当前回合序号",
        variable_type="整数",
        default_value=1,
        is_global=False,
        description="关卡实体变量：当前回合序号（1~总回合数）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_dialogue_lines__测试项目",
        variable_name="第七关_本回合_对白列表",
        variable_type="字符串列表",
        default_value=[" "],
        is_global=False,
        description="关卡实体变量：本回合对白列表缓存（供『对话』按钮循环展示）。",
        metadata={"category": "第七关/关卡实体"},
    ),
    LevelVariableDefinition(
        variable_id="var_level7_round_dialogue_index__测试项目",
        variable_name="第七关_本回合_对白序号",
        variable_type="整数",
        default_value=0,
        is_global=False,
        description="关卡实体变量：本回合对白序号（对话按钮递增，超出则回绕）。",
        metadata={"category": "第七关/关卡实体"},
    ),
]

