from __future__ import annotations

# 仅用于类型检查工具（如 Pyright/Pylance）识别的“占位类型定义”。
# 运行时无任何行为，仅提供名称以避免“未定义类型”提示。
# 节点图验证仍以 runtime/node_graph_validator.py 的注解解析为准。
#
# 注意：为减少误报（例如 range(0, 行上界) 中行上界的类型检查错误），
# 部分占位类型会继承对应的内置类型，使其在静态分析时具备基本的兼容性。


class 实体: ...


class GUID(str):
    ...


class 整数(int):
    ...


class 布尔值(int):
    ...


class 浮点数(float):
    ...


class 字符串(str):
    ...


class 三维向量: ...


class 元件ID(int):
    ...


class 配置ID(int):
    ...


class 阵营(int):
    ...


class 字典(dict):
    ...


class 结构体: ...


class 实体列表(list[实体]):
    ...


class GUID列表(list[GUID]):
    ...


class 整数列表(list[整数]):
    ...


class 布尔值列表(list[布尔值]):
    ...


class 浮点数列表(list[浮点数]):
    ...


class 字符串列表(list[字符串]):
    ...


class 三维向量列表(list[三维向量]):
    ...


class 元件ID列表(list[元件ID]):
    ...


class 配置ID列表(list[配置ID]):
    ...


class 阵营列表(list[阵营]):
    ...


class 结构体列表(list[结构体]):
    ...


# 通用标记（一般不用于变量注解，仅作为端口类型存在）


class 泛型: ...


# 字典别名占位类型：用于键类型_值类型字典形式的注解，消除静态检查器对别名类型的未定义报错。
# 键支持：实体 / GUID / 整数 / 字符串 / 阵营 / 配置ID / 元件ID
# 值支持：除结构体与结构体列表外，本文件中声明的其余占位类型。

# 键：实体
class 实体_实体字典(dict): ...
class 实体_GUID字典(dict): ...
class 实体_整数字典(dict): ...
class 实体_布尔值字典(dict): ...
class 实体_浮点数字典(dict): ...
class 实体_字符串字典(dict): ...
class 实体_三维向量字典(dict): ...
class 实体_元件ID字典(dict): ...
class 实体_配置ID字典(dict): ...
class 实体_阵营字典(dict): ...
class 实体_字典字典(dict): ...
class 实体_实体列表字典(dict): ...
class 实体_GUID列表字典(dict): ...
class 实体_整数列表字典(dict): ...
class 实体_布尔值列表字典(dict): ...
class 实体_浮点数列表字典(dict): ...
class 实体_字符串列表字典(dict): ...
class 实体_三维向量列表字典(dict): ...
class 实体_元件ID列表字典(dict): ...
class 实体_配置ID列表字典(dict): ...
class 实体_阵营列表字典(dict): ...
class 实体_泛型字典(dict): ...

# 键：GUID
class GUID_实体字典(dict): ...
class GUID_GUID字典(dict): ...
class GUID_整数字典(dict): ...
class GUID_布尔值字典(dict): ...
class GUID_浮点数字典(dict): ...
class GUID_字符串字典(dict): ...
class GUID_三维向量字典(dict): ...
class GUID_元件ID字典(dict): ...
class GUID_配置ID字典(dict): ...
class GUID_阵营字典(dict): ...
class GUID_字典字典(dict): ...
class GUID_实体列表字典(dict): ...
class GUID_GUID列表字典(dict): ...
class GUID_整数列表字典(dict): ...
class GUID_布尔值列表字典(dict): ...
class GUID_浮点数列表字典(dict): ...
class GUID_字符串列表字典(dict): ...
class GUID_三维向量列表字典(dict): ...
class GUID_元件ID列表字典(dict): ...
class GUID_配置ID列表字典(dict): ...
class GUID_阵营列表字典(dict): ...
class GUID_泛型字典(dict): ...

# 键：整数
class 整数_实体字典(dict): ...
class 整数_GUID字典(dict): ...
class 整数_整数字典(dict): ...
class 整数_布尔值字典(dict): ...
class 整数_浮点数字典(dict): ...
class 整数_字符串字典(dict): ...
class 整数_三维向量字典(dict): ...
class 整数_元件ID字典(dict): ...
class 整数_配置ID字典(dict): ...
class 整数_阵营字典(dict): ...
class 整数_字典字典(dict): ...
class 整数_实体列表字典(dict): ...
class 整数_GUID列表字典(dict): ...
class 整数_整数列表字典(dict): ...
class 整数_布尔值列表字典(dict): ...
class 整数_浮点数列表字典(dict): ...
class 整数_字符串列表字典(dict): ...
class 整数_三维向量列表字典(dict): ...
class 整数_元件ID列表字典(dict): ...
class 整数_配置ID列表字典(dict): ...
class 整数_阵营列表字典(dict): ...
class 整数_泛型字典(dict): ...

# 键：字符串
class 字符串_实体字典(dict): ...
class 字符串_GUID字典(dict): ...
class 字符串_整数字典(dict): ...
class 字符串_布尔值字典(dict): ...
class 字符串_浮点数字典(dict): ...
class 字符串_字符串字典(dict): ...
class 字符串_三维向量字典(dict): ...
class 字符串_元件ID字典(dict): ...
class 字符串_配置ID字典(dict): ...
class 字符串_阵营字典(dict): ...
class 字符串_字典字典(dict): ...
class 字符串_实体列表字典(dict): ...
class 字符串_GUID列表字典(dict): ...
class 字符串_整数列表字典(dict): ...
class 字符串_布尔值列表字典(dict): ...
class 字符串_浮点数列表字典(dict): ...
class 字符串_字符串列表字典(dict): ...
class 字符串_三维向量列表字典(dict): ...
class 字符串_元件ID列表字典(dict): ...
class 字符串_配置ID列表字典(dict): ...
class 字符串_阵营列表字典(dict): ...
class 字符串_泛型字典(dict): ...

# 键：阵营
class 阵营_实体字典(dict): ...
class 阵营_GUID字典(dict): ...
class 阵营_整数字典(dict): ...
class 阵营_布尔值字典(dict): ...
class 阵营_浮点数字典(dict): ...
class 阵营_字符串字典(dict): ...
class 阵营_三维向量字典(dict): ...
class 阵营_元件ID字典(dict): ...
class 阵营_配置ID字典(dict): ...
class 阵营_阵营字典(dict): ...
class 阵营_字典字典(dict): ...
class 阵营_实体列表字典(dict): ...
class 阵营_GUID列表字典(dict): ...
class 阵营_整数列表字典(dict): ...
class 阵营_布尔值列表字典(dict): ...
class 阵营_浮点数列表字典(dict): ...
class 阵营_字符串列表字典(dict): ...
class 阵营_三维向量列表字典(dict): ...
class 阵营_元件ID列表字典(dict): ...
class 阵营_配置ID列表字典(dict): ...
class 阵营_阵营列表字典(dict): ...
class 阵营_泛型字典(dict): ...

# 键：配置ID
class 配置ID_实体字典(dict): ...
class 配置ID_GUID字典(dict): ...
class 配置ID_整数字典(dict): ...
class 配置ID_布尔值字典(dict): ...
class 配置ID_浮点数字典(dict): ...
class 配置ID_字符串字典(dict): ...
class 配置ID_三维向量字典(dict): ...
class 配置ID_元件ID字典(dict): ...
class 配置ID_配置ID字典(dict): ...
class 配置ID_阵营字典(dict): ...
class 配置ID_字典字典(dict): ...
class 配置ID_实体列表字典(dict): ...
class 配置ID_GUID列表字典(dict): ...
class 配置ID_整数列表字典(dict): ...
class 配置ID_布尔值列表字典(dict): ...
class 配置ID_浮点数列表字典(dict): ...
class 配置ID_字符串列表字典(dict): ...
class 配置ID_三维向量列表字典(dict): ...
class 配置ID_元件ID列表字典(dict): ...
class 配置ID_配置ID列表字典(dict): ...
class 配置ID_阵营列表字典(dict): ...
class 配置ID_泛型字典(dict): ...

# 键：元件ID
class 元件ID_实体字典(dict): ...
class 元件ID_GUID字典(dict): ...
class 元件ID_整数字典(dict): ...
class 元件ID_布尔值字典(dict): ...
class 元件ID_浮点数字典(dict): ...
class 元件ID_字符串字典(dict): ...
class 元件ID_三维向量字典(dict): ...
class 元件ID_元件ID字典(dict): ...
class 元件ID_配置ID字典(dict): ...
class 元件ID_阵营字典(dict): ...
class 元件ID_字典字典(dict): ...
class 元件ID_实体列表字典(dict): ...
class 元件ID_GUID列表字典(dict): ...
class 元件ID_整数列表字典(dict): ...
class 元件ID_布尔值列表字典(dict): ...
class 元件ID_浮点数列表字典(dict): ...
class 元件ID_字符串列表字典(dict): ...
class 元件ID_三维向量列表字典(dict): ...
class 元件ID_元件ID列表字典(dict): ...
class 元件ID_配置ID列表字典(dict): ...
class 元件ID_阵营列表字典(dict): ...
class 元件ID_泛型字典(dict): ...


