from __future__ import annotations

from typing import Any

# 类型桩（stub）：为 Graph Code 的“共享复合节点名(...)”扩展语法糖提供补全。
# - 运行时不生效，仅用于编辑器智能提示与静态检查
# - 由内部生成流程从 `assets/资源库/共享/复合节点库/**/*.py` 自动生成（禁止手工编辑）

def 三元表达式_整数(*args: Any, **kwargs: Any) -> Any: ...
def 三元表达式_浮点数(*args: Any, **kwargs: Any) -> Any: ...
def 冷却_检查并更新时间戳(*args: Any, **kwargs: Any) -> Any: ...
def 实体列表_按布尔掩码过滤(*args: Any, **kwargs: Any) -> Any: ...
def 实体列表_按权重随机选实体(*args: Any, **kwargs: Any) -> Any: ...
def 实体列表_按评分取前K(*args: Any, **kwargs: Any) -> Any: ...
def 实体列表_查找首次出现序号(*args: Any, **kwargs: Any) -> Any: ...
def 布尔值列表_任意为真(*args: Any, **kwargs: Any) -> Any: ...
def 布尔值列表_全部为真(*args: Any, **kwargs: Any) -> Any: ...
def 整数_正模运算(*args: Any, **kwargs: Any) -> Any: ...
def 整数列表_切片(*args: Any, **kwargs: Any) -> Any: ...
def 整数列表_按布尔掩码过滤(*args: Any, **kwargs: Any) -> Any: ...
def 整数列表_按键分组(*args: Any, **kwargs: Any) -> Any: ...
def 整数列表_查找首次出现序号(*args: Any, **kwargs: Any) -> Any: ...
def 整数列表_求和(*args: Any, **kwargs: Any) -> Any: ...
def 整数列表_统计出现次数(*args: Any, **kwargs: Any) -> Any: ...
def 权重列表_随机选序号(*args: Any, **kwargs: Any) -> Any: ...


