from __future__ import annotations

"""
ui_guid_registry_format.py

集中定义 `ui_guid_registry.json` 的**文件格式**（兼容读、统一写）。

背景：
- `ui_guid_registry.json` 曾在多个链路中作为 UIKey→GUID 映射的落盘形式；
- 历史上 loader/兼容逻辑落在 `ui_patchers/*guid_registry*` 中，导致非 patcher 模块产生依赖反转；
- 该模块将“纯格式/IO 规则”收敛到稳定位置，供：
  - 导出记录快照（ui_export_records）
  - 运行时缓存读取（ui_guid_registry）
  - bundle sidecar 写出（pipelines/project_export_gia_parts）
  复用。

约定（兼容两种形态）：
- v1（推荐写出）：{"version": 1, "ui_key_to_guid": {"K": 123}, "updated_at": "..."}
- legacy/手工：{"K": 123, ...}
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Mapping


def load_ui_guid_registry_mapping(path: Path) -> dict[str, int]:
    """
    读取 `ui_guid_registry.json` 并返回 mapping（仅保留 guid>0）。

    - 文件不存在：返回空 dict（与历史 loader 行为一致）。
    - value 允许 int 或 “数字字符串”；其它类型 fail-fast。
    """
    p = Path(path).resolve()
    if not p.exists():
        return {}

    obj = json.loads(p.read_text(encoding="utf-8"))

    # 兼容两种形态：
    # - {"version": 1, "ui_key_to_guid": {...}}
    # - {"SomeKey": 123, ...}（早期/手工映射）
    mapping_obj: Any
    if isinstance(obj, dict) and "ui_key_to_guid" in obj:
        mapping_obj = obj.get("ui_key_to_guid")
    else:
        mapping_obj = obj

    if not isinstance(mapping_obj, dict):
        raise ValueError(f"ui_guid_registry 不是 dict：path={p}")

    out: dict[str, int] = {}
    for k, v in mapping_obj.items():
        key = str(k or "").strip()
        if key == "":
            continue

        # bool 是 int 的子类：显式拒绝，避免 True/False 混入 registry
        if isinstance(v, bool):
            raise ValueError(f"ui_guid_registry value 不能是 bool：key={key!r} value={v!r} path={p}")

        guid: int
        if isinstance(v, int):
            guid = int(v)
        elif isinstance(v, str) and v.strip().isdigit():
            guid = int(v.strip())
        else:
            raise ValueError(f"ui_guid_registry value 不是 int：key={key!r} value={v!r} path={p}")

        if guid <= 0:
            continue
        out[key] = int(guid)
    return out


def write_ui_guid_registry_file(
    path: Path,
    ui_key_to_guid: Mapping[str, int],
    *,
    updated_at: str | None = None,
) -> None:
    """
    将 mapping 写出为 v1 registry 文件（不做历史备份；由调用方决定是否需要 history）。
    """
    p = Path(path).resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    cleaned: dict[str, int] = {}
    for k, v in dict(ui_key_to_guid or {}).items():
        key = str(k or "").strip()
        if key == "":
            continue
        if isinstance(v, bool) or not isinstance(v, int):
            raise TypeError(f"ui_key_to_guid value must be int (not bool): key={key!r} value={v!r}")
        guid = int(v)
        if guid <= 0:
            continue
        cleaned[key] = int(guid)

    saved_at = str(updated_at or "").strip() or datetime.now().isoformat(timespec="seconds")
    payload = {
        "version": 1,
        "ui_key_to_guid": {k: int(cleaned[k]) for k in sorted(cleaned.keys())},
        "updated_at": saved_at,
        "note": "Generated by Graph_Generater: UIKey→GUID registry file (runtime/bundle sidecar).",
    }
    p.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _ui_guid_registry_history_dir(registry_path: Path) -> Path:
    # 与 registry 同级，避免跨目录写盘导致“找不到历史”
    return Path(registry_path).resolve().parent / "ui_guid_registry_history"


def _append_ui_guid_registry_history_line(
    *,
    registry_path: Path,
    saved_at: str,
    mapping_total: int,
    history_file: Path,
    backup_file: Path | None,
) -> None:
    history_file.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "saved_at": str(saved_at),
        "registry_path": str(Path(registry_path).resolve()),
        "mapping_total": int(mapping_total),
        "backup_file": (str(Path(backup_file).resolve()) if backup_file is not None else None),
    }
    with Path(history_file).open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def _backup_existing_ui_guid_registry(registry_path: Path, *, saved_at: str) -> Path | None:
    p = Path(registry_path).resolve()
    if not p.exists():
        return None

    history_dir = _ui_guid_registry_history_dir(p).resolve()
    history_dir.mkdir(parents=True, exist_ok=True)

    # 备份内容保持“原样”，不尝试 parse（避免历史文件格式/缩进差异导致信息丢失）
    old_text = p.read_text(encoding="utf-8")

    # 文件名用时间戳，必要时自动去重
    base_name = f"ui_guid_registry_{str(saved_at).replace(':', '').replace('-', '').replace('T', '_')}.json"
    backup_path = (history_dir / base_name).resolve()
    if backup_path.exists():
        i = 2
        while True:
            candidate = (history_dir / f"{backup_path.stem}__{i}{backup_path.suffix}").resolve()
            if not candidate.exists():
                backup_path = candidate
                break
            i += 1

    backup_path.write_text(old_text, encoding="utf-8")
    return backup_path


def save_ui_guid_registry(
    path: Path,
    ui_key_to_guid: Mapping[str, int],
    *,
    updated_at: str | None = None,
) -> None:
    """
    保存 `ui_guid_registry.json`（v1 格式），并在同级目录写入历史留档：
    - ui_guid_registry_history/<timestamp>.json
    - ui_guid_registry_history/history.jsonl（JSONL 记录）
    """
    p = Path(path).resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    # 保持历史行为：对无效条目做“清理丢弃”，而非直接抛错
    cleaned: dict[str, int] = {}
    for k, v in dict(ui_key_to_guid or {}).items():
        key = str(k or "").strip()
        if key == "":
            continue
        if not isinstance(v, int) or isinstance(v, bool):
            continue
        guid = int(v)
        if guid <= 0:
            continue
        cleaned[key] = int(guid)

    saved_at = str(updated_at or "").strip() or datetime.now().isoformat(timespec="seconds")
    backup_file = _backup_existing_ui_guid_registry(p, saved_at=saved_at)
    history_file = (_ui_guid_registry_history_dir(p) / "history.jsonl").resolve()
    _append_ui_guid_registry_history_line(
        registry_path=p,
        saved_at=saved_at,
        mapping_total=len(cleaned),
        history_file=history_file,
        backup_file=backup_file,
    )

    # 统一写出格式：v1 + stable sorting
    write_ui_guid_registry_file(p, cleaned, updated_at=saved_at)


__all__ = [
    "load_ui_guid_registry_mapping",
    "write_ui_guid_registry_file",
    "save_ui_guid_registry",
]

