"""Graph canvas固定配色表。

这些颜色仅用于节点图画布及其图形项，不随浅色/深色主题切换，确保画布在所有模式下保持一致外观。
"""


class GraphPalette:
    # 画布与网格
    CANVAS_BG = "#1E1E1E"
    GRID_LIGHT = "#2A2A2A"
    GRID_BOLD = "#3A3A3A"

    # 基础文本与边框
    TEXT_BRIGHT = "#FFFFFF"
    TEXT_LABEL = "#E0E0E0"
    TEXT_SECONDARY = "#A0A0A0"
    BORDER_MUTED = "#3A3A3A"
    BORDER_SUBTLE = "#444444"

    # 节点内容区
    NODE_CONTENT_BG = "#1F1F1F"
    NODE_CONTENT_BORDER = "#3A3A3A"
    NODE_DEFAULT_FALLBACK = "#555555"

    # 输入控件
    INPUT_BG = "#2A2A2A"
    INPUT_BORDER = "#3A3A3A"
    INPUT_BORDER_HOVER = "#5A5A5A"
    INPUT_TOP_BORDER = "#E0E0E0"

    # 验证提示
    WARN_GOLD = "#FFD700"
    WARN_ORANGE = "#FFA500"
    INFO_SKY = "#87CEEB"

    # 边/连线色
    EDGE_FLOW_SELECTED = "#FF6B35"
    EDGE_DATA_SELECTED = "#00BCD4"
    EDGE_BRANCH_YES = "#4CAF50"
    EDGE_BRANCH_NO = "#F44336"
    EDGE_FLOW_MAIN = "#FFD700"
    EDGE_DATA = "#5A9FD4"

    # 端口与标签
    PORT_EXPOSED_TAG_START = "#FFD700"
    PORT_EXPOSED_TAG_END = "#FFA500"
    PORT_EXPOSED_TAG_OUTLINE = "#CC8800"
    PORT_DEFAULT_INPUT = "#D0D0D0"
    PORT_DEFAULT_OUTPUT = "#FFFFFF"
    PORT_HIGHLIGHT_DATA = "#00FF00"
    PORT_EXPOSED_FILL_ALPHA = 50  # 仅用于填充时设置透明度

    # 类别颜色（标题栏渐变）
    CATEGORY_QUERY = "#2D5FE3"
    CATEGORY_EVENT = "#FF5E9C"
    CATEGORY_COMPUTE = "#2FAACB"
    CATEGORY_EXECUTION = "#9CD64B"
    CATEGORY_FLOW = "#FF9955"
    CATEGORY_DEFAULT = "#555555"
    CATEGORY_QUERY_DARK = "#1B3FA8"
    CATEGORY_EVENT_DARK = "#C23A74"
    CATEGORY_COMPUTE_DARK = "#1D6F8A"
    CATEGORY_EXECUTION_DARK = "#6BA633"
    CATEGORY_FLOW_DARK = "#E87722"
    CATEGORY_VIRTUAL_IN = "#AA55FF"
    CATEGORY_VIRTUAL_OUT = "#55AAFF"
    CATEGORY_VIRTUAL_IN_DARK = "#8833DD"
    CATEGORY_VIRTUAL_OUT_DARK = "#3388DD"

    # 叠层徽标与调试
    BADGE_ACCENT = "#FFAA00"
    BADGE_FILL = "#FFD400"
    BADGE_OUTLINE = "#000000"

    # 顶部按钮（自动排版）
    BTN_PRIMARY = "#4A9EFF"
    BTN_PRIMARY_HOVER = "#5AAFFF"
    BTN_PRIMARY_PRESSED = "#3A8EEF"
    BTN_DISABLED_BG = "#666666"
    BTN_DISABLED_TEXT = "#999999"


