from __future__ import annotations

from typing import Any, Dict

STRUCT_ID = 'test'
STRUCT_TYPE = 'basic'

STRUCT_PAYLOAD: Dict[str, Any] = {'type': 'Struct',
 'struct_ype': 'basic',
 'name': 'test',
 'value': [{'key': '新增变量1', 'param_type': '阵营列表', 'value': {'param_type': '阵营列表', 'value': []}},
           {'key': '整数', 'param_type': '整数', 'value': {'param_type': '整数', 'value': '0'}},
           {'key': '新增变量4', 'param_type': '浮点数', 'value': {'param_type': '浮点数', 'value': '0.00'}},
           {'key': '新增变量5', 'param_type': '布尔值', 'value': {'param_type': '布尔值', 'value': 'False'}},
           {'key': '新增变量6', 'param_type': '三维向量', 'value': {'param_type': '三维向量', 'value': '0,0,0'}},
           {'key': '新增变量7', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '0'}},
           {'key': '新增变量8', 'param_type': 'GUID', 'value': {'param_type': 'GUID', 'value': '0'}},
           {'key': '新增变量9', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '0'}},
           {'key': '新增变量10', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '0'}},
           {'key': '新增变量11', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '0'}},
           {'key': '新增变量12', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '0'}},
           {'key': '新增变量13', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '0'}},
           {'key': '新增变量14',
            'param_type': '结构体',
            'value': {'param_type': '结构体', 'value': {'structId': '1077936129', 'type': 'Struct', 'value': []}}},
           {'key': '新增变量15',
            'param_type': '字典',
            'value': {'param_type': '字典',
                      'value': {'type': 'Dict',
                                'key_type': 'String',
                                'value_type': 'String',
                                'value': [{'key': {'param_type': '字符串', 'value': '213'},
                                           'value': {'param_type': '字符串', 'value': '123'}}]}}},
           {'key': '新增变量16',
            'param_type': '结构体列表',
            'value': {'param_type': '结构体列表', 'value': {'structId': '1077936130', 'value': []}}},
           {'key': '新增变量17', 'param_type': '实体', 'value': {'param_type': '实体', 'value': ''}},
           {'key': '新增变量18', 'param_type': '实体', 'value': {'param_type': '实体', 'value': ''}},
           {'key': '新增变量19', 'param_type': '实体', 'value': {'param_type': '实体', 'value': ''}},
           {'key': '新增变量20', 'param_type': 'GUID列表', 'value': {'param_type': 'GUID列表', 'value': []}},
           {'key': '新增变量21', 'param_type': '三维向量列表', 'value': {'param_type': '三维向量列表', 'value': []}},
           {'key': '新增变量22', 'param_type': '布尔值列表', 'value': {'param_type': '布尔值列表', 'value': []}},
           {'key': '新增变量23', 'param_type': '浮点数列表', 'value': {'param_type': '浮点数列表', 'value': []}},
           {'key': '新增变量24', 'param_type': '浮点数列表', 'value': {'param_type': '浮点数列表', 'value': []}},
           {'key': '新增变量25', 'param_type': '整数列表', 'value': {'param_type': '整数列表', 'value': []}},
           {'key': '新增变量26', 'param_type': '字符串列表', 'value': {'param_type': '字符串列表', 'value': []}},
           {'key': '123', 'param_type': '实体', 'value': {'param_type': '实体', 'value': '432'}}]}
