from __future__ import annotations

import re
from typing import Dict

from ugc_file_tools.custom_variables.constants import (
    DEFAULT_VARIABLE_GROUP_NAME,
    ITEM_DISPLAY_UNBOUND_GROUP_ID_SENTINEL_UINT64_MAX,
    KNOWN_VARIABLE_GROUP_ID_BY_NAME,
    UNBOUND_GROUP_ID_SENTINEL_UINT64_MAX,
)
from ugc_file_tools.custom_variables.web_ui_constants import (
    DEFAULT_ITEM_DISPLAY_BUTTON_CONFIG_ID_VARIABLE_FULL_NAME,
    DEFAULT_ITEM_DISPLAY_BUTTON_COOLDOWN_SECONDS_VARIABLE_FULL_NAME,
    DEFAULT_ITEM_DISPLAY_BUTTON_QUANTITY_DEFAULT,
    DEFAULT_ITEM_DISPLAY_BUTTON_QUANTITY_VARIABLE_FULL_NAME,
    DEFAULT_PROGRESSBAR_INT_DEFAULTS,
    DEFAULT_SHARED_PROGRESSBAR_VARIABLE_NAMES,
)

UI_SCHEMA_LABEL_TEXTBOX = "textbox"
UI_SCHEMA_LABEL_ITEM_DISPLAY = "item_display"
UI_SCHEMA_LABEL_PROGRESSBAR = "progressbar"

UI_KEY_GROUP_TAIL_RECT_RE = re.compile(r"^r\d+_\d+_\d+_\d+$")
UI_KEY_GROUP_TAIL_DUP_RE = re.compile(r"^dup(_\d+)?$")

