"""战斗/管理资源任务配置表，供 Todo 任务策略复用"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


@dataclass(frozen=True)
class ResourceTaskConfig:
    attribute_name: str
    task_prefix: str
    title_format: str
    detail_type: str
    description: str
    guide: str = ""
    id_field: str = "resource_id"
    task_type: str = ""
    is_singleton: bool = False
    singleton_id: str = ""
    default_display_name: str = ""


COMBAT_RESOURCE_CONFIGS: Sequence[ResourceTaskConfig] = (
    ResourceTaskConfig(
        attribute_name="player_templates",
        task_prefix="combat:player_template",
        title_format="玩家模板：{name}",
        detail_type="combat_player_template",
        description="配置玩家模板（玩家基础属性与默认职业）",
        guide="1. 切换到战斗预设模式\n2. 选择'玩家模板'标签\n3. 配置玩家的默认属性与关联职业",
        id_field="template_id",
        task_type="combat",
    ),
    ResourceTaskConfig(
        attribute_name="player_classes",
        task_prefix="combat:player_class",
        title_format="职业：{name}",
        detail_type="combat_player_class",
        description="配置职业属性与战斗数值",
        guide="1. 切换到战斗预设模式\n2. 选择'职业'标签\n3. 配置职业属性",
        id_field="class_id",
        task_type="combat",
    ),
    ResourceTaskConfig(
        attribute_name="unit_statuses",
        task_prefix="combat:unit_status",
        title_format="单位状态：{name}",
        detail_type="combat_unit_status",
        description="配置单位状态效果",
        guide="1. 切换到战斗预设模式\n2. 选择'单位状态'标签\n3. 配置状态数值",
        id_field="status_id",
        task_type="combat",
    ),
    ResourceTaskConfig(
        attribute_name="skills",
        task_prefix="combat:skill",
        title_format="技能：{name}",
        detail_type="combat_skill",
        description="配置技能效果",
        guide="1. 切换到战斗预设模式\n2. 选择'技能'标签\n3. 配置技能参数",
        id_field="skill_id",
        task_type="combat",
    ),
    ResourceTaskConfig(
        attribute_name="projectiles",
        task_prefix="combat:projectile",
        title_format="投射物：{name}",
        detail_type="combat_projectile",
        description="配置投射物行为",
        guide="1. 切换到战斗预设模式\n2. 选择'投射物'标签\n3. 录入参数",
        id_field="projectile_id",
        task_type="combat",
    ),
    ResourceTaskConfig(
        attribute_name="items",
        task_prefix="combat:item",
        title_format="战斗道具：{name}",
        detail_type="combat_item",
        description="配置战斗道具属性",
        guide="1. 切换到战斗预设模式\n2. 选择'道具'标签\n3. 配置道具效果",
        id_field="item_id",
        task_type="combat",
    ),
)


MANAGEMENT_RESOURCE_CONFIGS: Sequence[ResourceTaskConfig] = (
    ResourceTaskConfig(
        attribute_name="timers",
        task_prefix="management:timer",
        title_format="计时器：{name}",
        detail_type="management_timer",
        description="配置全局计时器",
        guide="1. 切换到管理面板\n2. 选择'计时器'标签\n3. 配置计时器参数",
        id_field="timer_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="level_variables",
        task_prefix="management:level_variable",
        title_format="关卡变量：{name}",
        detail_type="management_level_variable",
        description="维护关卡层级变量",
        guide="1. 切换到管理面板\n2. 选择'关卡变量'标签\n3. 录入变量及默认值",
        id_field="variable_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="preset_points",
        task_prefix="management:preset_point",
        title_format="预设点：{name}",
        detail_type="management_preset_point",
        description="维护预设点坐标与属性",
        guide="1. 切换到管理面板\n2. 选择'预设点'标签\n3. 配置位置与参数",
        id_field="preset_point_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="skill_resources",
        task_prefix="management:skill_resource",
        title_format="技能资源：{name}",
        detail_type="management_skill_resource",
        description="管理技能资源池",
        guide="1. 切换到管理面板\n2. 选择'技能资源'标签\n3. 配置资源曲线",
        id_field="skill_resource_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="currency_backpack",
        task_prefix="management:currency_backpack",
        title_format="货币与背包配置",
        detail_type="management_currency_backpack",
        description="配置货币与背包容量",
        guide="1. 切换到管理面板\n2. 选择'货币/背包'标签\n3. 录入初始数值",
        id_field="config_id",
        task_type="management",
        is_singleton=True,
        singleton_id="currency_backpack",
        default_display_name="全局配置",
    ),
    ResourceTaskConfig(
        attribute_name="equipment_data",
        task_prefix="management:equipment",
        title_format="装备：{name}",
        detail_type="management_equipment",
        description="配置装备条目",
        guide="1. 切换到管理面板\n2. 选择'装备'标签\n3. 录入属性",
        id_field="equipment_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="shop_templates",
        task_prefix="management:shop_template",
        title_format="商店：{name}",
        detail_type="management_shop",
        description="配置商店模板",
        guide="1. 切换到管理面板\n2. 选择'商店'标签\n3. 配置商品与价格",
        id_field="shop_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="ui_layouts",
        task_prefix="management:ui_layout",
        title_format="界面布局：{name}",
        detail_type="management_ui_layout",
        description="管理界面布局结构",
        guide="1. 切换到管理面板\n2. 选择'界面布局'标签\n3. 排列控件",
        id_field="layout_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="ui_widget_templates",
        task_prefix="management:ui_widget_template",
        title_format="界面控件：{name}",
        detail_type="management_ui_widget",
        description="配置界面控件模板",
        guide="1. 切换到管理面板\n2. 选择'界面控件'标签\n3. 配置属性",
        id_field="widget_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="multi_language",
        task_prefix="management:multi_language",
        title_format="多语言：{name}",
        detail_type="management_multi_language",
        description="维护多语言文本",
        guide="1. 切换到管理面板\n2. 选择'多语言'标签\n3. 录入翻译文本",
        id_field="locale_key",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="main_cameras",
        task_prefix="management:main_camera",
        title_format="主镜头：{name}",
        detail_type="management_main_camera",
        description="配置主镜头",
        guide="1. 切换到管理面板\n2. 选择'主镜头'标签\n3. 调整参数",
        id_field="camera_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="light_sources",
        task_prefix="management:light_source",
        title_format="光源：{name}",
        detail_type="management_light_source",
        description="配置关卡光源",
        guide="1. 切换到管理面板\n2. 选择'光源'标签\n3. 录入灯光参数",
        id_field="light_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="background_music",
        task_prefix="management:background_music",
        title_format="背景音乐：{name}",
        detail_type="management_background_music",
        description="配置背景音乐资源",
        guide="1. 切换到管理面板\n2. 选择'背景音乐'标签\n3. 绑定音轨",
        id_field="music_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="paths",
        task_prefix="management:path",
        title_format="路径：{name}",
        detail_type="management_path",
        description="配置路径节点",
        guide="1. 切换到管理面板\n2. 选择'路径'标签\n3. 调整路点",
        id_field="path_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="entity_deployment_groups",
        task_prefix="management:deployment_group",
        title_format="布设组：{name}",
        detail_type="management_deployment_group",
        description="配置实体布设组",
        guide="1. 切换到管理面板\n2. 选择'布设组'标签\n3. 配置成员",
        id_field="group_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="unit_tags",
        task_prefix="management:unit_tag",
        title_format="单位标签：{name}",
        detail_type="management_unit_tag",
        description="维护单位标签",
        guide="1. 切换到管理面板\n2. 选择'单位标签'标签\n3. 编辑标签",
        id_field="tag_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="scan_tags",
        task_prefix="management:scan_tag",
        title_format="扫描标签：{name}",
        detail_type="management_scan_tag",
        description="维护扫描标签",
        guide="1. 切换到管理面板\n2. 选择'扫描标签'标签\n3. 配置规则",
        id_field="scan_tag_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="shields",
        task_prefix="management:shield",
        title_format="护盾：{name}",
        detail_type="management_shield",
        description="配置护盾属性",
        guide="1. 切换到管理面板\n2. 选择'护盾'标签\n3. 配置能量参数",
        id_field="shield_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="peripheral_systems",
        task_prefix="management:peripheral_system",
        title_format="外围系统：{name}",
        detail_type="management_peripheral_system",
        description="配置外围系统",
        guide="1. 切换到管理面板\n2. 选择'外围系统'标签\n3. 配置流程",
        id_field="system_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="save_points",
        task_prefix="management:save_point",
        title_format="局内存档模板：{name}",
        detail_type="management_save_point",
        description="配置局内存档",
        guide="1. 切换到管理面板\n2. 选择'局内存档管理'标签\n3. 配置模板条目与启用状态",
        id_field="save_point_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="chat_channels",
        task_prefix="management:chat_channel",
        title_format="聊天频道：{name}",
        detail_type="management_chat_channel",
        description="配置聊天频道",
        guide="1. 切换到管理面板\n2. 选择'聊天频道'标签\n3. 配置权限",
        id_field="channel_id",
        task_type="management",
    ),
    ResourceTaskConfig(
        attribute_name="level_settings",
        task_prefix="management:level_settings",
        title_format="关卡设置",
        detail_type="management_level_settings",
        description="配置关卡级别参数",
        guide="1. 切换到管理面板\n2. 选择'关卡设置'标签\n3. 配置全局参数",
        id_field="config_id",
        task_type="management",
        is_singleton=True,
        singleton_id="level_settings",
        default_display_name="整体配置",
    ),
)
