from __future__ import annotations

from typing import Any, Dict

# 本文件由 tools/generate_struct_and_signal_definitions.py 自动生成。
# 结构体定义以 Python 字典常量形式固化为 STRUCT_DEFINITION_PAYLOADS。
# 运行时不再依赖 assets/资源库/管理配置/结构体定义 下的 JSON 文件。

STRUCT_DEFINITION_PAYLOADS: Dict[str, Dict[str, Any]] = {
    'BOSS关卡配置': {'type': 'Struct', 'struct_ype': 'basic', 'name': 'BOSS关卡配置', 'value': [{'key': 'BOSS_关卡ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': 'BOSS_目标BOSSID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': 'BOSS_难度层级', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '1'}}, {'key': '奖励_BOSS碎片_目标BOSSID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_BOSS碎片_数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_符文碎片数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_宝石碎片数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    'BOSS碎片条目': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': 'BOSS碎片条目', 'value': [{'key': 'BOSS_ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '碎片数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    'struct_all_supported_types_example': {'type': 'Struct', 'struct_ype': 'basic', 'name': 'struct_all_supported_types_example', 'value': [{'key': '实体字段', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': 'GUID字段', 'param_type': 'Guid', 'value': {'param_type': 'Guid', 'value': '00000000'}}, {'key': '整数字段', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '布尔值字段', 'param_type': 'Bool', 'value': {'param_type': 'Bool', 'value': 'False'}}, {'key': '浮点数字段', 'param_type': 'Float', 'value': {'param_type': 'Float', 'value': '0.0'}}, {'key': '字符串字段', 'param_type': 'String', 'value': {'param_type': 'String', 'value': '示例字符串'}}, {'key': '阵营字段', 'param_type': 'Camp', 'value': {'param_type': 'Camp', 'value': '022'}}, {'key': '三维向量字段', 'param_type': 'Vector3', 'value': {'param_type': 'Vector3', 'value': '0,0,0'}}, {'key': '元件ID字段', 'param_type': 'ComponentId', 'value': {'param_type': 'ComponentId', 'value': '0'}}, {'key': '配置ID字段', 'param_type': 'ConfigId', 'value': {'param_type': 'ConfigId', 'value': '0'}}, {'key': '结构体字段', 'param_type': 'Struct', 'value': {'param_type': 'Struct', 'value': {'structId': '', 'type': 'Struct', 'value': []}}}, {'key': '字典字段', 'param_type': 'Dict', 'value': {'param_type': 'Dict', 'value': {'type': 'Dict', 'key_type': 'String', 'value_type': 'String', 'value': [{'key': {'param_type': 'String', 'value': '示例键111'}, 'value': {'param_type': 'String', 'value': '示例值11'}}, {'key': {'param_type': 'String', 'value': '123123122'}, 'value': {'param_type': 'String', 'value': '213212'}}]}}}, {'key': '实体列表字段', 'param_type': 'EntityList', 'value': {'param_type': 'EntityList', 'value': ['0', '123', '123', '123', '123123', '12']}}, {'key': 'GUID列表字段', 'param_type': 'GuidList', 'value': {'param_type': 'GuidList', 'value': ['00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', '', '']}}, {'key': '整数列表字段', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': ['1', '2', '3']}}, {'key': '布尔值列表字段', 'param_type': 'BoolList', 'value': {'param_type': 'BoolList', 'value': ['True', 'False']}}, {'key': '浮点数列表字段', 'param_type': 'FloatList', 'value': {'param_type': 'FloatList', 'value': ['1.0', '2.5']}}, {'key': '字符串列表字段', 'param_type': 'StringList', 'value': {'param_type': 'StringList', 'value': ['条目1', '条目2', '条目3']}}, {'key': '阵营列表字段', 'param_type': 'CampList', 'value': {'param_type': 'CampList', 'value': ['0', '1']}}, {'key': '三维向量列表字段', 'param_type': 'Vector3List', 'value': {'param_type': 'Vector3List', 'value': ['0,0,0', '1,2,3']}}, {'key': '元件ID列表字段', 'param_type': 'ComponentIdList', 'value': {'param_type': 'ComponentIdList', 'value': ['0', '1']}}, {'key': '配置ID列表字段', 'param_type': 'ConfigIdList', 'value': {'param_type': 'ConfigIdList', 'value': ['0', '1']}}, {'key': '结构体列表字段', 'param_type': 'StructList', 'value': {'param_type': 'StructList', 'value': {'structId': '', 'value': []}}}]},
    'test': {'type': 'Struct', 'struct_ype': 'basic', 'name': 'test', 'value': [{'key': '新增变量1', 'param_type': 'CampList', 'value': {'param_type': 'CampList', 'value': []}}, {'key': '整数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '新增变量4', 'param_type': 'Float', 'value': {'param_type': 'Float', 'value': '0.00'}}, {'key': '新增变量5', 'param_type': 'Bool', 'value': {'param_type': 'Bool', 'value': 'False'}}, {'key': '新增变量6', 'param_type': 'Vector3', 'value': {'param_type': 'Vector3', 'value': '0,0,0'}}, {'key': '新增变量7', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': '新增变量8', 'param_type': 'Guid', 'value': {'param_type': 'Guid', 'value': '0'}}, {'key': '新增变量9', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': '新增变量10', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': '新增变量11', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': '新增变量12', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': '新增变量13', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '0'}}, {'key': '新增变量14', 'param_type': 'Struct', 'value': {'param_type': 'Struct', 'value': {'structId': '1077936129', 'type': 'Struct', 'value': []}}}, {'key': '新增变量15', 'param_type': 'Dict', 'value': {'param_type': 'Dict', 'value': {'type': 'Dict', 'key_type': 'String', 'value_type': 'String', 'value': [{'key': {'param_type': 'String', 'value': '213'}, 'value': {'param_type': 'String', 'value': '123'}}]}}}, {'key': '新增变量16', 'param_type': 'StructList', 'value': {'param_type': 'StructList', 'value': {'structId': '1077936130', 'value': []}}}, {'key': '新增变量17', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': ''}}, {'key': '新增变量18', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': ''}}, {'key': '新增变量19', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': ''}}, {'key': '新增变量20', 'param_type': 'GuidList', 'value': {'param_type': 'GuidList', 'value': []}}, {'key': '新增变量21', 'param_type': 'Vector3List', 'value': {'param_type': 'Vector3List', 'value': []}}, {'key': '新增变量22', 'param_type': 'BoolList', 'value': {'param_type': 'BoolList', 'value': []}}, {'key': '新增变量23', 'param_type': 'FloatList', 'value': {'param_type': 'FloatList', 'value': []}}, {'key': '新增变量24', 'param_type': 'FloatList', 'value': {'param_type': 'FloatList', 'value': []}}, {'key': '新增变量25', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '新增变量26', 'param_type': 'StringList', 'value': {'param_type': 'StringList', 'value': []}}, {'key': '123', 'param_type': 'Entity', 'value': {'param_type': 'Entity', 'value': '432'}}]},
    '冒险关卡配置': {'type': 'Struct', 'struct_ype': 'basic', 'name': '冒险关卡配置', 'value': [{'key': '关卡_关卡ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '关卡_主题怪物分类列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': ['0']}}, {'key': '难度_预算数值', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '难度_怪物基础等级', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '1'}}, {'key': '关卡_是否BOSS关卡', 'param_type': 'Bool', 'value': {'param_type': 'Bool', 'value': 'False'}}, {'key': '奖励_钻石', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '掉落_规则ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '掉落_BOSS规则ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_BOSS碎片_目标BOSSID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_BOSS碎片_数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_符文碎片数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '奖励_宝石碎片数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '怪物_怪物GUID列表', 'param_type': 'GuidList', 'value': {'param_type': 'GuidList', 'value': ['0']}}, {'key': '怪物_数量列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': ['1']}}, {'key': '怪物_是否小BOSS列表', 'param_type': 'BoolList', 'value': {'param_type': 'BoolList', 'value': ['False']}}, {'key': '怪物_所属波次索引列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': ['1']}}]},
    '战斗天赋节点等级条目': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '战斗天赋节点等级条目', 'value': [{'key': '天赋节点ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '节点等级', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '技能碎片条目': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '技能碎片条目', 'value': [{'key': '技能ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '碎片数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '玩家天赋状态': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '玩家天赋状态', 'value': [{'key': '天赋_锻造天赋_节点ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '天赋_锻造天赋_等级列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '天赋_战斗天赋_节点ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '天赋_战斗天赋_等级列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '天赋_剩余天赋点数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '天赋_累计重置次数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '玩家存档': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '玩家存档', 'value': [{'key': '元信息_存档版本', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '1'}}, {'key': '元信息_创建时间', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '元信息_更新时间', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '元信息_累计游玩时长秒', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '进度_当前关卡ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '1'}}, {'key': '进度_当前BOSSID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '玩家背包': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '玩家背包', 'value': [{'key': '背包_武器条目ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '背包_符文条目ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '背包_宝石条目ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '背包_特殊道具_配置ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '背包_特殊道具_数量列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}]},
    '玩家资源与货币': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '玩家资源与货币', 'value': [{'key': '资源_钻石', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '资源_金币', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '资源_BOSS碎片_BOSSID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '资源_BOSS碎片_数量列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '资源_符文碎片总量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '资源_宝石碎片总量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '资源_技能碎片_技能ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '资源_技能碎片_数量列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}, {'key': '资源_天赋重置令数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '资源_激活中的产出卡ID列表', 'param_type': 'Int32List', 'value': {'param_type': 'Int32List', 'value': []}}]},
    '玩家锻造状态': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '玩家锻造状态', 'value': [{'key': '锻造状态_累计锻造次数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '锻造状态_高稀有度保底计数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '锻造状态_技能保底计数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '锻造状态_高插槽保底计数', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '锻造状态_累计锻造消耗钻石', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '锻造状态_累计锻造获得金币', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '背包材料条目': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '背包材料条目', 'value': [{'key': '材料配置ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '材料数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '背包特殊道具条目': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '背包特殊道具条目', 'value': [{'key': '道具配置ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '道具数量', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
    '锻造天赋节点等级条目': {'type': 'Struct', 'struct_ype': 'ingame_save', 'name': '锻造天赋节点等级条目', 'value': [{'key': '天赋节点ID', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}, {'key': '节点等级', 'param_type': 'Int32', 'value': {'param_type': 'Int32', 'value': '0'}}]},
}

def list_struct_ids() -> list[str]:
    """返回所有可用的结构体 ID 列表（排序后）。"""
    return sorted(STRUCT_DEFINITION_PAYLOADS.keys())

def get_struct_payload(struct_id: str) -> Dict[str, Any] | None:
    """按 ID 获取单个结构体定义载荷的浅拷贝，未找到时返回 None。"""
    key = str(struct_id)
    payload = STRUCT_DEFINITION_PAYLOADS.get(key)
    if payload is None:
        return None
    return dict(payload)
